using Microsoft.EntityFrameworkCore.Migrations;

namespace Asp.Migrations
{
    public partial class AutoGeneratedIds : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
